name: pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pipeline:
    uses: bjuvensjo/actions-test/.github/workflows/pipeline-workflow.yml@main
